title: Using setTimeout to add a pause
hero_image: images/banner.png
description: Using setTimeout to add a pause
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Using setTimeout to add a pause
